### ISSUE TITLE
muốn hợp tác

### ISSUE THREAD

**Issue by nguyluky** [huukhuong/TKB_SGU_Extension#5]
chào bạn. tôi thấy rất là hướng thú với extension của bạn. tôi cũng có một xếp thời khóa biểu (tkbsgusort.id.vn). có vấn đề là khi đăng kí môn học xong thì không biết thời khóa biểu mình xếp với mình đã đăng kí khác nhau chỗ nào. vì vậy tôi muốn hợp tác với bạn tạo một tính năng có thể so sánh giữa tkb của trang tôi và tkb hiện tại.

hi vọng chúng ta có thể hợp tác với nhau.
cảm ơn vì đã đọc.

**Comment by nguyluky** [comment]
thực ra là em (k23) muốn học hỏi thôi =)

**Comment by thekids1002** [comment]
Thank you for your amazing idea! However, I haven't fully understood the requirements yet and would love to discuss further details.
You can reach me via [Facebook](https://www.facebook.com/thekids.1002/).
Once again, thank you for sharing this interesting idea!

------------------------------------------------------------

Cảm ơn bạn vì ý tưởng rất tuyệt vời! Tuy nhiên, mình chưa hiểu rõ hoàn toàn về yêu cầu, rất mong có thể bàn thêm chi tiết. 
Bạn có thể liên hệ với mình qua [Facebook](https://www.facebook.com/thekids.1002/)
Một lần nữa, cảm ơn bạn vì đã chia sẻ ý tưởng thú vị này!
